### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by slomo** [megadix/jfcm#1]
Is there are a particular reason why the library is not available on maven central? After all it is the central platform for java FOSS projects and given JFCM high release number it should also be mature enough to be published to the world.

**Comment by megadix** [comment]
Hi Slomo,
you're absolutely right, it has been in my "todo list" since version 1.0.0
The problem is that it requires some bureaucracy and many small technical details, so I didn't (yet) find the time to do it.

Users seem comfortable with the instructions on the website
http://jfcm.megadix.it/book/documentation/getting-started/download-and-installation

so I never put much effort in this activity.
However...

**Comment by jitpack-io** [comment]
Hi 
Perhaps this will help in the meantime https://jitpack.io/#megadix/jfcm/v1.4.2

**Comment by megadix** [comment]
Yeah definitely!
I'll add it to the docs, thank you

**Comment by megadix** [comment]
Finally in the docs:
http://jfcm.megadix.it/book/documentation/getting-started/download-and-installation
