### ISSUE TITLE
FcmIO.java cannot load the right weight of connections from XML files

### ISSUE THREAD

**Issue by ForgingAhead** [megadix/jfcm#2]
Hi Dimitri,

I've been playing with the JFCM library. I found that the _parseParams(Node elem, XPath xpath)_ method in _FcmIO.java_ has an error for it cannot load the weight correctly from XML files - the resulting weights in CognitiveMap are all 1.0 rather than what's specified in the XML file.

Just to let you know. :-)

**Comment by megadix** [comment]
Hi Chen,
I could not reproduce this error, can you add more details?

- which version of JFCM are you using?
- can you attach an example XML file that is not correctly loaded?

Thank you,
Dimitri

**Comment by ForgingAhead** [comment]
Hi Dimitri,

I am running V1.4.2.

One example is running the Samples - WildlifePark.java which read
WildlifePark.fcm.xml. Then I printed the resulting CognitiveMap.

Here is part of the output:

 connections = [{[Black market price - Poachers] weight=1.0,
delay=0}{[Erbivores - Black market price] weight=1.0, delay=0}{[Erbivores -
Grassland] weight=1.0, delay=0}{[Erbivores - Poachers] weight=1.0, delay=0}

In the XML, the connection "Erbivores - Black market price" has a weight
value -0.2, "Erbivores - Grassland" -0.6, and the next 0.3.

Please find the attached WildlifePark.fcm.xml. BTW, I've fixed the problem,
if it's a problem, in *parseParams.*

Thanks,
Feng

2017-05-11 11:19 GMT+01:00 Dimitri De Franciscis <notifications@github.com>:

**Comment by megadix** [comment]
Hi Chen,
I've found where the problem is: `WildlifePark.fcm.xml` has syntax errors! This is likely a legacy from an old version of the library.

While I'm working on fixing examples and documentation, you could use a corrected version of the file:
[WildlifePark.fcm.xml](https://gist.github.com/megadix/1bb541c237213c0cb541eba9d1b77c86)

Summary of the changes:

1) change XSD declaration

- from `<maps xmlns="http://www.megadix.org/standards/JFCM-map-v-1.0">`
- to: `<maps xmlns="http://www.megadix.org/standards/JFCM-map-v-1.2">`

2) for each `<connection>` element, wrap `<param>` in an additional `<params>` (note the *'s'*)


Thank you for helping me improve JFCM!

**Comment by ForgingAhead** [comment]
Oh, I see. Yes, I noticed the missing of the <params> in the old xml file.
Great. Thank you for the information.

All the best,
Feng

2017-05-11 13:35 GMT+01:00 Dimitri De Franciscis <notifications@github.com>:

**Comment by megadix** [comment]
Fixed examples in `master` branch, see:  
https://github.com/megadix/jfcm-samples/tree/master/src/main/resources/org/megadix/jfcm/samples
